# Generated by Django 3.2 on 2022-07-11 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('volume_dispensed', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not Done')], default='not_done', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales Management',
                'db_table': 'sales',
            },
        ),
    ]
